galaxy_info:
  author: Abdoul B Alarou
  description: Provide timescaledb installation
  license: MIT
  min_ansible_version: 2.4
  platforms:
  - name: Debian
    versions:
    - stretch
    - jessie
    - buster
  - name: Ubuntu
    versions:
    - bionic
    - xenial
    - trusty
    - cosmic
    - disco
  galaxy_tags:
    - timescaledb
dependencies:
  - agora-PostgreSQL
