---
# defaults file for egeneralov.timescaledb

pgdg_version: 11
pgdg_supported_versions:
  - 9.6
  - 10
  - 11

supported_distribution:
  Debian:
    - stretch
    - jessie
  Ubuntu:
    - bionic

tdb_postgresql_conf:
  - { "k": "shared_preload_libraries", "v": "'timescaledb'" }
  - { "k": "timescaledb.telemetry_level", "v": "off" }

#pgdg_users:
#  - user: root
#    password: root
#    database: root

pgdg_users:
  - user: "{{ postgres_user }}"
    password: "{{ postgres_password }}"
    database: "{{ postgres_name }}"

repo_url:
  Debian: "deb https://packagecloud.io/timescale/timescaledb/{{ ansible_distribution | lower }}/ {{ ansible_distribution_release }} main"
  Ubuntu: "deb http://ppa.launchpad.net/timescale/timescaledb-ppa/{{ ansible_distribution | lower }}/ {{ ansible_distribution_release }} main"
