---
##This playbook will install and configured node exporter and target nodes"
#This node exporter is for Premetheus and Grafana setup.
#
- hosts: "{{ hosts_inventory }}"
  become: yes
  tags: exporter

  tasks:
    - name: create node exporter user
      user:
        name: node_exporter
        shell: /bin/false
        create_home: no

    - name: create /app directory
      file:
        path: /app
        state: directory

    - name: Download and extract the Node Exporter binary
      unarchive:
        src: https://github.com/prometheus/node_exporter/releases/download/v0.18.1/node_exporter-0.18.1.linux-amd64.tar.gz
        dest: /app
        remote_src: yes

    - name: Copy the Node Exporter binary to the appropriate location and set ownership
      copy:
        src: /app/node_exporter-0.18.1.linux-amd64/node_exporter
        dest: /usr/local/bin/
        owner: node_exporter
        group: node_exporter
        mode: 0755
        remote_src: yes

    - name: Create a systemd unit file for Node Exporter by copying templating systemd file
      template:
        src: templates/node_expoter_systemd.j2
        dest: /etc/systemd/system/node_exporter.service
        mode: '0644'
        owner: root
        group: root

    - name: Just force systemd to reread configs (2.4 and above)
      systemd:
        daemon_reload: yes

    - name: Start and enable the node_exporter service
      service:
        name: node_exporter.service
        enabled: yes
        state: started

- hosts:  "{{ hosts_inventory }}"
  become: yes
  tags: prometheus

  tasks:
    - name: copy prometheus configuration file over
      template:
        src: templates/prometheus.j2
        dest: /etc/prometheus/prometheus.yml
        mode: '0644'
        owner: prometheus
        group: prometheus
        backup: yes
      notify:
        - restart prometheus

#    - name: Start and enable the node_exporter service
#      service:
#        name: prometheus.service
#        enabled: yes
#        state: restarted
